WIP: rewrite comment_box as functional
liqd/adhocracy4 pull request #1116
Opened 2022-06-14 14:59 UTC by goapunk

2022-06-15 13:59 UTC, goapunk commented on adhocracy4/comments_async/static/comments_async/comment_box.jsx
> +  function setReplyError (parentIndex, index, message) {
I've added a bunch of convenient functions for the error handling as I found it hard to read

2022-06-15 14:00 UTC, goapunk commented on adhocracy4/comments_async/static/comments_async/comment_box.jsx
> +          parentIndex,
merged the two setState calls into one here

2022-06-16 08:01 UTC, phillimorland approved these changes
thats all i've found so far

2022-06-16 08:30 UTC, goapunk commented on adhocracy4/comments_async/static/comments_async/comment_box.jsx
> +                  commentCategoryChoices={props.commentCategoryChoices}
nice catch! fixed

2022-06-16 08:32 UTC, khamui reviewed
Very nice! It is working mostly fine.
What I didn't test, but it looks fine from code:

- Scroll Event listener
- Errorhandling

what i did test:
- post/edit/delete comments and subcomments
- TOS behavior (that seems to be handled in the other PR)
- sort/filter/search

2022-06-16 08:33 UTC, khamui requested changes

2022-06-16 08:33 UTC, khamui commented on adhocracy4/comments_async/static/comments_async/comment_box.jsx
> +  function handleCommentModify (modifiedComment, index, parentIndex) {
probably leftover `this.updateStateComment...` , `this` needs to be removed.

2022-06-16 08:35 UTC, goapunk commented on adhocracy4/comments_async/static/comments_async/comment_box.jsx
> +  const [useTermsOfUse, setUseTermsOfUse] = useState(true)
good point, I set it to false

2022-06-16 08:59 UTC, khamui approved these changes

2022-06-16 11:48 UTC, phillimorland commented
this doesn't help but maybe more people will comment https://github.com/facebook/react/issues/24696

2022-09-26 10:32 UTC, phillimorland approved these changes
looking good.
tested the scroll and error and found (parts Kha didn't):
the auto scroll for anchored comments works 
errors work however the auto focus that browsers have to `role=alert` is not working however this seems also broken on dev. so nothing to do with this pr :)

2022-09-26 10:32 UTC, merged