WIP [7776] django upgrade to 4.2 (LTS)
liqd/adhocracy4 pull request #1504
Opened 2023-11-07 15:44 UTC by m4ra

2023-11-08 08:53 UTC, goapunk commented
> Django 4 has dropped support for sha1 hashes. The deprecation warning was there before Django v3. From the release notes:
> 
>     * Support for the pre-Django 3.1 password reset tokens in the admin site (that use the SHA-1 hashing algorithm) will be removed.
> 
>     * Support for the pre-Django 3.1 django.core.signing.Signer signatures (encoded with the SHA-1 algorithm) will be removed.
> 
>     * Support for the pre-Django 3.1 django.core.signing.dumps() signatures (encoded with the SHA-1 algorithm) in django.core.signing.loads() will be removed.
> 
>     * Support for the pre-Django 3.1 user sessions (that use the SHA-1 algorithm) will be removed.
> 
> 
> @goapunk will that affect existing passwords? or was it dealt previously while upgrading to 3.2? Cannot find if this is dealt by Django itself. See transitional notes [here](https://docs.djangoproject.com/en/4.2/releases/3.1/#default-hashing-algorithm-settings), though is about updating multiple instances of same project.
> 
> Notes: need to update django-allauth for 4.2

I'm not entirely sure, but worst case the very few affected users would have to request a new password via `forgot password`. So I think that's ok. I also vaguely remembered checking for passwords with old hashes in the db and didn't find any.

2023-11-27 08:35 UTC, goapunk requested changes
@m4ra there are some instances of `index_together` which should be replaced with `indexes` as described here: https://docs.djangoproject.com/en/4.2/releases/4.2/

2023-11-27 13:09 UTC, m4ra commented
> @m4ra there are some instances of index_together which should be replaced with indexes as described here: https://docs.djangoproject.com/en/4.2/releases/4.2/#index-together-option-is-deprecated-in-favor-of-indexes
@goapunk done, and rebased. Please have another look.

2023-11-28 14:03 UTC, m4ra commented on adhocracy4/modules/models.py
>      )
then we delete the fields with the custom BlueprintType?
Also the new migration cancels the 0008. If we remove 0008, it won't generate 0009 here
@goapunk

2023-11-30 07:46 UTC, goapunk commented on Makefile
> -	$(VIRTUAL_ENV)/bin/python manage.py makemigrations --dry-run --check --noinput || EXIT_STATUS=$$?; \
we don't need to remove these anymore, right?

2023-11-30 08:01 UTC, goapunk commented on adhocracy4/categories/form_fields.py
> -class CategoryIconDict(abc.Mapping):
I'm not really sure why this was needed so I removed it, I think we should point out to testers to verify everything still works as intended with the icons

2023-11-30 13:45 UTC, goapunk commented on adhocracy4/projects/migrations/0043_migrate_topics_to_m2m_topics.py
> +                    name=[item[1] for item in topicsenum if item[0] == topic_code][0],
topicsenum -> topicenum

2023-12-04 13:53 UTC, goapunk requested changes
Looks good to me, we only need changelogs for the latest changes (topics, categories?, blueprint_types?) and maybe some of my commits should be squashed

2023-12-04 15:45 UTC, m4ra commented
> Looks good to me, we only need changelogs for the latest changes (topics, categories?, blueprint_types?) and maybe some of my commits should be squashed

@goapunk done, have another look please.
FYI I kept the models changes related to choices in separate commits in case we need to revert.

2023-12-04 16:12 UTC, goapunk approved these changes
really nice!

2023-12-04 16:12 UTC, merged