WIP: apps/dashboard: validate that phases of the same module don't overlap
liqd/adhocracy4 pull request #585
Opened 2020-09-14 07:24 UTC by fuzzylogic2000

2020-09-24 15:29 UTC, phillimorland reviewed
I think it works but my tests are failing anyway

2020-09-25 12:21 UTC, Rineee requested changes
Cool, the not opverlapping phase validation works! But now the validation start_date < end_date doesn't work:
`

Exception Type: | KeyError
-- | --
'end_date'

`

2020-10-06 11:00 UTC, Rineee approved these changes

2020-10-06 11:00 UTC, Rineee commented
Superawesomecool!!

2020-10-06 11:01 UTC, merged